import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/context/AppContext";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { dark } from "@clerk/themes";
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={`${outfit.className} antialiased text-gray-700`}>
          <AppContextProvider>
            {children}  
            <Toaster position="top-right" />
          </AppContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
